### PR TITLE
Add shared "xcproj" scheme for building from command line

### PR DESCRIPTION
**Pull request by sharplet**
This enables homebrew to build from HEAD.

### CODE REVIEW

**Comment by keith** [comment]
+1 this would be great to have, thanks for submitting it @sharplet !

**Comment by 0xced** [comment]
Thanks @sharplet and sorry it took so long to merge. I also released version 0.2.1 with Xcode 8 support.

**Comment by keith** [comment]
I've submitted a PR to homebrew to update the HEAD branch name https://github.com/Homebrew/homebrew-core/pull/6668

**Comment by sharplet** [comment]
No problem, thanks! 🎉

**Pull request merged**
