### PR TITLE
New add-source command

### PR DESCRIPTION
**Pull request by keith**
This command adds source paths to the project under a given group name. Here's some example usage:

```
xcproj add-source Foo/Bar.* Foo
```

Will add all files matching that glob to the Foo group.

```
xcproj add-source Foo.* Bar/Baz
```

Will add all the matching files to the group Baz nested under Bar.

```
xcproj add-source Foo.* Bar.* root
```

Will add all matching Foo and Bar files to the root group of the project.

Please let me know if you see anything that can be improved here. I also tried to match the coding style so let me know if I need to change anything there. Thanks!

### CODE REVIEW

**Comment by keith** [comment]
I have another command I've added, would probably make sense as a separate pull though.

**Comment by 0xced** [comment]
Thinking a bit about it, maybe there should be only one `add-files` command that would take additional arguments instead of `add-xcconfig`, `add-source`, `add-resources-bundle` etc. What do you think? 

Some example usages I have in mind:

Add `debug.xcconfig` in the Configurations group and set the `Debug` configuration based on it:

```
xcproj add-files --group Configurations --base Debug debug.xcconfig
```

---

Add `warnings.xcconfig` at the root of the project and set the `Debug` and `Release` configurations based on it:

```
xcproj add-files --base Debug --base Release warnings.xcconfig
```

---

Add `play.png`  and `pause.png` in the `MyApp/Resources/Images` group and add them to the default _Copy Bundle Resources_ phase:

```
xcproj add-files --group MyApp/Resources/Images --phase Resource play.png pause.png
```

---

Add `MyGreatLibrary.a` in the `Frameworks` group and add it to the default _Link Binary With Libraries_ phase:

```
xcproj add-files --group Frameworks --phase Link MyGreatLibrary.a
```

---

Add `Employee.m` and `Company.m` in the `Sources/Model` group and add it to the default _Compile Sources_ phase:

```
xcproj add-files --group Sources/Model --phase SourceCode Employee.m Company.m
```

**Comment by keith** [comment]
Yep I think this makes perfect sense. I can jump on this sometime soon.

**Comment by 0xced** [comment]
Excellent! :smiley:

**Comment by keith** [comment]
It seems like DDCLI doesn't have support for command specific flags. These commands would end up having to be like:

```
xcproj --group Sources/Model --phase SourceCode add-files Employee.m Company.m
```

What do you think about that/any suggestions?

**Comment by keith** [comment]
Poke

**Comment by Michenux** [comment]
It's a great pull request.
What we need is (from command line) :
- add file to a group
- remove file from a group
- add a group to a group
- remove group from a group
- add localization plist files

Possible ?

**Comment by keith** [comment]
@Michenux I believe so. I'm not sure what the interface for that would look like though.

**Pull request closed without merging**
